### ISSUE TITLE
存在题目一样，而选项不一样的情况

### ISSUE THREAD

**Issue by adobemercury** [251321639/wechat_brain#9]
感觉应该把题目和4个选项写在sqlite的一个UNIQUE列，只有题目，选项完全一样才算同样的题

**Comment by adobemercury** [comment]
Question: 小米公司是哪年成立的？
绝对正确答案:2010年
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/watchdog/observers/api.py", line 199, in run
    self.dispatch_events(self.event_queue, self.timeout)
  File "/usr/local/lib/python3.5/dist-packages/watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/usr/local/lib/python3.5/dist-packages/watchdog/events.py", line 330, in dispatch
    _method_map[event_type](event)
  File "/mnt/file/My File/Graduate/2017~2018/wechat_brain/answer.py", line 85, in on_created
    quiz = read_question(f)
  File "/mnt/file/My File/Graduate/2017~2018/wechat_brain/answer.py", line 33, in read_question
    adbshell.tap('option' + str(options.index(sql_result)))
ValueError: '2010年' is not in list


这次的题目选项中没有“年”字
